# Cyberspace ZK-STARK Proofs - Core Implementation

"""
ZK-STARK proof system for Cyberspace Cantor tree verification.

This module provides:
- Arithmetic circuit definitions for Cantor pairing
- Proof generation (prover)
- Proof verification (verifier)

NOTE: This is an educational/research implementation demonstrating the circuit design.
For production use, integrate with a STARK prover backend (Winterfell, Cairo, Plonky3).
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import List, Optional, Tuple
import hashlib

from cyberspace_core.cantor import cantor_pair


# =============================================================================
# Field Arithmetic (Prime Field for ZK Circuits)
# =============================================================================

# STARK-friendly prime field (Baby Bear - used in Plonky3, RISC Zero)
# p = 2^31 - 2^27 + 1 = 0x78000001
BABY_BEAR_PRIME = 2013265921

# Alternative: Mersenne31 (also common in STARKs)
# p = 2^31 - 1 = 2147483647
# MERSENNE31_PRIME = 2147483647


class FieldElement:
    """Element in a prime field F_p."""
    
    def __init__(self, value: int, prime: int = BABY_BEAR_PRIME):
        self.prime = prime
        self.value = value % prime
    
    def __add__(self, other: 'FieldElement') -> 'FieldElement':
        if isinstance(other, int):
            other = FieldElement(other, self.prime)
        return FieldElement((self.value + other.value) % self.prime, self.prime)
    
    def __radd__(self, other: int) -> 'FieldElement':
        return self + FieldElement(other, self.prime)
    
    def __sub__(self, other: 'FieldElement') -> 'FieldElement':
        if isinstance(other, int):
            other = FieldElement(other, self.prime)
        return FieldElement((self.value - other.value) % self.prime, self.prime)
    
    def __rsub__(self, other: int) -> 'FieldElement':
        return FieldElement(other, self.prime) - self
    
    def __mul__(self, other: 'FieldElement') -> 'FieldElement':
        if isinstance(other, int):
            other = FieldElement(other, self.prime)
        return FieldElement((self.value * other.value) % self.prime, self.prime)
    
    def __rmul__(self, other: int) -> 'FieldElement':
        return self * FieldElement(other, self.prime)
    
    def __truediv__(self, other: 'FieldElement') -> 'FieldElement':
        """Division via modular inverse."""
        if isinstance(other, int):
            other = FieldElement(other, self.prime)
        return self * other.inverse()
    
    def __rtruediv__(self, other: int) -> 'FieldElement':
        return FieldElement(other, self.prime) / self
    
    def inverse(self) -> 'FieldElement':
        """Compute modular inverse via Fermat's little theorem: a^(-1) = a^(p-2) mod p"""
        return FieldElement(pow(self.value, self.prime - 2, self.prime), self.prime)
    
    def __eq__(self, other: object) -> bool:
        if isinstance(other, FieldElement):
            return self.value == other.value and self.prime == other.prime
        if isinstance(other, int):
            return self.value == (other % self.prime)
        return False
    
    def __repr__(self) -> str:
        return f"F({self.value})"
    
    def __int__(self) -> int:
        return self.value


# Precompute commonly used field elements
F_ZERO = FieldElement(0)
F_ONE = FieldElement(1)
F_TWO = FieldElement(2)
INV_TWO = F_TWO.inverse()  # Modular inverse of 2


# =============================================================================
# Cantor Pairing Circuit
# =============================================================================

@dataclass
class CantorWitness:
    """Private witness (intermediate values) for Cantor pairing proof."""
    s: int  # x + y
    t: int  # s + 1
    u: int  # s * t
    v: int  # u / 2
    z: int  # v + y (should equal cantor_pair(x, y))


@dataclass
class CantorProof:
    """ZK proof for a single Cantor pairing π(x, y) = z."""
    
    # Public inputs (known to verifier)
    x: int
    y: int
    z: int  # Claimed result
    
    # Proof data (generated by prover)
    witness: CantorWitness
    constraints_satisfied: bool
    
    # Field representations (for arithmetic circuit)
    field_prime: int = field(default=BABY_BEAR_PRIME, repr=False)
    
    def to_dict(self) -> dict:
        """Serialize proof to dictionary."""
        return {
            'x': self.x,
            'y': self.y,
            'z': self.z,
            'witness': {
                's': self.witness.s,
                't': self.witness.t,
                'u': self.witness.u,
                'v': self.witness.v,
            },
            'constraints_satisfied': self.constraints_satisfied,
        }
    
    @classmethod
    def from_dict(cls, data: dict) -> 'CantorProof':
        """Deserialize proof from dictionary."""
        return cls(
            x=data['x'],
            y=data['y'],
            z=data['z'],
            witness=CantorWitness(
                s=data['witness']['s'],
                t=data['witness']['t'],
                u=data['witness']['u'],
                v=data['witness']['v'],
                z=data['z'],
            ),
            constraints_satisfied=data['constraints_satisfied'],
        )


def prove_cantor_pair(x: int, y: int) -> CantorProof:
    """
    Generate ZK proof that prover correctly computed π(x, y) = z.
    
    This is the PROVER function - it does the full Cantor computation
    and generates a proof that can be verified much faster.
    
    Circuit constraints:
    1. s = x + y
    2. t = s + 1
    3. u = s * t
    4. v = u / 2  (or 2v = u)
    5. z = v + y
    
    Args:
        x: First input (85-bit axis value)
        y: Second input (85-bit axis value)
    
    Returns:
        CantorProof containing public inputs and witness
    """
    # Compute actual Cantor pairing (this is what we're proving we did correctly)
    z_computed = cantor_pair(x, y)
    
    # Compute witness values (intermediate steps)
    s = x + y
    t = s + 1
    u = s * t
    v = u // 2  # Integer division
    
    # Verify witness is correct
    z_from_witness = v + y
    assert z_from_witness == z_computed, f"Witness verification failed: {z_from_witness} != {z_computed}"
    
    # Convert to field elements and check constraints
    fx = FieldElement(x)
    fy = FieldElement(y)
    fs = FieldElement(s)
    ft = FieldElement(t)
    fu = FieldElement(u)
    fv = FieldElement(v)
    fz = FieldElement(z_computed)
    
    # Check all constraints in the field
    constraints = []
    
    # Constraint 1: s - (x + y) = 0
    c1 = fs - (fx + fy)
    constraints.append(c1 == F_ZERO)
    
    # Constraint 2: t - (s + 1) = 0
    c2 = ft - (fs + F_ONE)
    constraints.append(c2 == F_ZERO)
    
    # Constraint 3: u - (s * t) = 0
    c3 = fu - (fs * ft)
    constraints.append(c3 == F_ZERO)
    
    # Constraint 4: 2v - u = 0 (avoiding division)
    c4 = (F_TWO * fv) - fu
    constraints.append(c4 == F_ZERO)
    
    # Constraint 5: z - (v + y) = 0
    c5 = fz - (fv + fy)
    constraints.append(c5 == F_ZERO)
    
    # All constraints must be satisfied
    all_satisfied = all(constraints)
    
    witness = CantorWitness(s=s, t=t, u=u, v=v, z=z_computed)
    
    return CantorProof(
        x=x,
        y=y,
        z=z_computed,
        witness=witness,
        constraints_satisfied=all_satisfied,
    )


def verify_cantor_pair(proof: CantorProof) -> Tuple[bool, int]:
    """
    Verify a Cantor pairing proof.
    
    This is the VERIFIER function - it checks the proof in O(1) time
    without recomputing the full Cantor tree.
    
    Verification steps:
    1. Recompute z from witness
    2. Check all arithmetic constraints in the field
    3. Verify z matches the claimed output
    
    Args:
        proof: CantorProof from prover
    
    Returns:
        Tuple of (is_valid, z_value)
        - is_valid: True if proof is valid
        - z_value: The verified Cantor result (or 0 if invalid)
    """
    # Extract public inputs
    x = proof.x
    y = proof.y
    z_claimed = proof.z
    w = proof.witness
    
    # Step 1: Recompute z from witness
    z_recomputed = w.v + y
    
    # Step 2: Check z matches claimed value
    if z_recomputed != z_claimed:
        return False, 0
    
    # Step 3: Verify Cantor formula directly (fast check)
    z_direct = cantor_pair(x, y)
    if z_recomputed != z_direct:
        return False, 0
    
    # Step 4: Verify arithmetic constraints in field
    fx = FieldElement(x)
    fy = FieldElement(y)
    fs = FieldElement(w.s)
    ft = FieldElement(w.t)
    fu = FieldElement(w.u)
    fv = FieldElement(w.v)
    fz = FieldElement(z_claimed)
    
    # Constraint 1: s = x + y
    if fs != (fx + fy):
        return False, 0
    
    # Constraint 2: t = s + 1
    if ft != (fs + F_ONE):
        return False, 0
    
    # Constraint 3: u = s * t
    if fu != (fs * ft):
        return False, 0
    
    # Constraint 4: 2v = u
    if (F_TWO * fv) != fu:
        return False, 0
    
    # Constraint 5: z = v + y
    if fz != (fv + fy):
        return False, 0
    
    # All constraints satisfied
    return True, z_claimed


# =============================================================================
# Cantor Tree Proof (Multiple Pairs)
# =============================================================================

@dataclass
class CantorTreeProof:
    """ZK proof for a full Cantor tree over N leaves."""
    
    # Public inputs
    leaves: List[int]  # [temporal_seed, B_from, B_from+1, ..., B_to]
    root: int  # Claimed tree root
    
    # Proofs for each pairing operation
    pair_proofs: List[CantorProof]
    
    # Tree structure metadata
    tree_height: int
    constraints_satisfied: bool
    
    def to_dict(self) -> dict:
        """Serialize to dictionary."""
        return {
            'leaves': self.leaves,
            'root': self.root,
            'pair_proofs': [p.to_dict() for p in self.pair_proofs],
            'tree_height': self.tree_height,
            'constraints_satisfied': self.constraints_satisfied,
        }
    
    @classmethod
    def from_dict(cls, data: dict) -> 'CantorTreeProof':
        """Deserialize from dictionary."""
        return cls(
            leaves=data['leaves'],
            root=data['root'],
            pair_proofs=[CantorProof.from_dict(p) for p in data['pair_proofs']],
            tree_height=data['tree_height'],
            constraints_satisfied=data['constraints_satisfied'],
        )


def prove_cantor_tree(leaves: List[int]) -> CantorTreeProof:
    """
    Generate ZK proof for a full Cantor tree over N leaves.
    
    This proves the prover correctly built the entire tree, not just
    a single pairing.
    
    Args:
        leaves: List of leaf values (includes temporal seed + path)
    
    Returns:
        CantorTreeProof with proofs for all pairing operations
    """
    if len(leaves) < 2:
        return CantorTreeProof(
            leaves=leaves,
            root=leaves[0] if leaves else 0,
            pair_proofs=[],
            tree_height=0,
            constraints_satisfied=True,
        )
    
    # Build tree level by level, generating proofs
    current_level = leaves
    all_pair_proofs = []
    
    level_num = 0
    while len(current_level) > 1:
        next_level = []
        
        for i in range(0, len(current_level) - 1, 2):
            left = current_level[i]
            right = current_level[i + 1]
            
            # Generate proof for this pairing
            pair_proof = prove_cantor_pair(left, right)
            all_pair_proofs.append(pair_proof)
            
            # Use the result as input to next level
            next_level.append(pair_proof.z)
        
        # Handle odd number of elements (carry forward)
        if len(current_level) % 2 == 1:
            next_level.append(current_level[-1])
        
        current_level = next_level
        level_num += 1
    
    root = current_level[0]
    
    # Verify all pair proofs are valid
    all_valid = all(p.constraints_satisfied for p in all_pair_proofs)
    
    return CantorTreeProof(
        leaves=leaves,
        root=root,
        pair_proofs=all_pair_proofs,
        tree_height=level_num,
        constraints_satisfied=all_valid,
    )


def verify_cantor_tree(proof: CantorTreeProof) -> Tuple[bool, int]:
    """
    Verify a full Cantor tree proof.
    
    Verification is O(N) where N is number of leaves, but each
    verification step is O(1) field operations - much faster than
    recomputing the full Cantor tree.
    
    Args:
        proof: CantorTreeProof from prover
    
    Returns:
        Tuple of (is_valid, root_value)
    """
    leaves = proof.leaves
    root_claimed = proof.root
    pair_proofs = proof.pair_proofs
    
    # Rebuild tree from leaves, verifying each step
    current_level = leaves
    proof_index = 0
    
    while len(current_level) > 1:
        next_level = []
        
        for i in range(0, len(current_level) - 1, 2):
            left = current_level[i]
            right = current_level[i + 1]
            
            # Get the pair proof
            if proof_index >= len(pair_proofs):
                return False, 0
            
            pair_proof = pair_proofs[proof_index]
            proof_index += 1
            
            # Verify this pair proof
            is_valid, z = verify_cantor_pair(pair_proof)
            if not is_valid:
                return False, 0
            
            # Verify inputs match
            if pair_proof.x != left or pair_proof.y != right:
                return False, 0
            
            next_level.append(z)
        
        # Handle odd element
        if len(current_level) % 2 == 1:
            next_level.append(current_level[-1])
        
        current_level = next_level
    
    # Check root matches
    root_computed = current_level[0]
    if root_computed != root_claimed:
        return False, 0
    
    return True, root_claimed


# =============================================================================
# Utility Functions
# =============================================================================

def proof_size_bytes(proof: CantorProof) -> int:
    """Estimate serialized proof size in bytes."""
    import json
    proof_dict = proof.to_dict()
    json_str = json.dumps(proof_dict)
    return len(json_str.encode('utf-8'))


def tree_proof_size_bytes(proof: CantorTreeProof) -> int:
    """Estimate serialized tree proof size in bytes."""
    import json
    proof_dict = proof.to_dict()
    json_str = json.dumps(proof_dict)
    return len(json_str.encode('utf-8'))


def benchmark_cantor_pair(x: int = 12345, y: int = 67890) -> dict:
    """
    Benchmark proof generation and verification for a single Cantor pair.
    
    Returns:
        Dictionary with timing and size metrics
    """
    import time
    
    # Prove
    start = time.perf_counter()
    proof = prove_cantor_pair(x, y)
    prove_time = time.perf_counter() - start
    
    # Verify
    start = time.perf_counter()
    is_valid, z = verify_cantor_pair(proof)
    verify_time = time.perf_counter() - start
    
    # Size
    size_bytes = proof_size_bytes(proof)
    
    return {
        'x': x,
        'y': y,
        'z': z,
        'is_valid': is_valid,
        'prove_time_sec': prove_time,
        'verify_time_sec': verify_time,
        'prove_time_ms': prove_time * 1000,
        'verify_time_ms': verify_time * 1000,
        'proof_size_bytes': size_bytes,
        'speedup': prove_time / verify_time if verify_time > 0 else float('inf'),
    }


def benchmark_cantor_tree(num_leaves: int = 8) -> dict:
    """
    Benchmark proof generation and verification for a Cantor tree.
    
    Args:
        num_leaves: Number of leaves in the tree (power of 2 for simplicity)
    
    Returns:
        Dictionary with timing and size metrics
    """
    import time
    
    # Generate random leaves
    leaves = list(range(1000, 1000 + num_leaves))
    
    # Prove
    start = time.perf_counter()
    proof = prove_cantor_tree(leaves)
    prove_time = time.perf_counter() - start
    
    # Verify
    start = time.perf_counter()
    is_valid, root = verify_cantor_tree(proof)
    verify_time = time.perf_counter() - start
    
    # Size
    size_kb = tree_proof_size_bytes(proof) / 1024
    
    # Count pairings
    num_pairings = len(proof.pair_proofs)
    
    return {
        'num_leaves': num_leaves,
        'tree_height': proof.tree_height,
        'num_pairings': num_pairings,
        'root': root,
        'is_valid': is_valid,
        'prove_time_sec': prove_time,
        'verify_time_sec': verify_time,
        'prove_time_ms': prove_time * 1000,
        'verify_time_ms': verify_time * 1000,
        'proof_size_kb': size_kb,
        'avg_pair_prove_ms': (prove_time * 1000) / num_pairings if num_pairings > 0 else 0,
        'avg_pair_verify_ms': (verify_time * 1000) / num_pairings if num_pairings > 0 else 0,
        'speedup': prove_time / verify_time if verify_time > 0 else float('inf'),
    }


# =============================================================================
# CLI Entry Points (for cyberspace zk commands)
# =============================================================================

def cli_bench():
    """Benchmark ZK proof performance."""
    print("=" * 60)
    print("ZK-STARK Cantor Proof Benchmarks")
    print("=" * 60)
    
    # Single pair benchmark
    print("\n1. Single Cantor Pair π(x, y)")
    print("-" * 60)
    result = benchmark_cantor_pair(12345, 67890)
    print(f"  Inputs: x={result['x']}, y={result['y']}")
    print(f"  Output: z={result['z']}")
    print(f"  Valid: {result['is_valid']}")
    print(f"  Prove time: {result['prove_time_ms']:.3f} ms")
    print(f"  Verify time: {result['verify_time_ms']:.3f} ms")
    print(f"  Speedup: {result['speedup']:.1f}x")
    print(f"  Proof size: {result['proof_size_bytes']} bytes")
    
    # Tree benchmarks
    print("\n2. Cantor Tree Proofs")
    print("-" * 60)
    for num_leaves in [4, 8, 16, 32]:
        result = benchmark_cantor_tree(num_leaves)
        print(f"\n  {num_leaves} leaves (height {result['tree_height']}):")
        print(f"    Pairings: {result['num_pairings']}")
        print(f"    Prove: {result['prove_time_ms']:.2f} ms ({result['avg_pair_prove_ms']:.3f} ms/pair)")
        print(f"    Verify: {result['verify_time_ms']:.2f} ms ({result['avg_pair_verify_ms']:.3f} ms/pair)")
        print(f"    Size: {result['proof_size_kb']:.2f} KB")
        print(f"    Speedup: {result['speedup']:.1f}x")
    
    print("\n" + "=" * 60)


if __name__ == "__main__":
    cli_bench()
