#!/usr/bin/env python3
"""Regenerate src/cyberspace_core/grandfathered.py from the spec repository.

CYBERSPACE_V2.md section 6.16 and DECK-0001 section 5.8 name, by event id, the
old-format sidesteps and rides that a verifier accepts without re-checking
their roots and openings. A verifier embeds the ids rather than fetching them
at runtime. The lists may grow once more, in a final census after the
reference clients start publishing the new formats; rerun this then:

    python scripts/gen_grandfathered.py --spec /path/to/cyberspace --ref origin/master

Both files are read at the given git ref, not from the working tree, so the
spec checkout can sit on any branch, and the resolved commit is written into
the generated module.
"""
from __future__ import annotations

import argparse
import re
import subprocess
from pathlib import Path
from typing import List, Tuple

SIDESTEPS = "grandfathered-v2-sidesteps.txt"
RIDES = "decks/grandfathered-v1-hyperjumps.txt"
OUT = Path(__file__).resolve().parents[1] / "src" / "cyberspace_core" / "grandfathered.py"
EVENT_ID = re.compile(r"[0-9a-f]{64}")


def parse_list(text: str) -> List[Tuple[str, str]]:
    """(event id, commentary) for every entry, in file order. Lines starting
    with # are comments; every other non-empty line starts with a 64-character
    lowercase hex event id, and anything after the id is commentary."""
    out: List[Tuple[str, str]] = []
    seen = set()
    for number, line in enumerate(text.splitlines(), 1):
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        head, _, rest = stripped.partition(" ")
        if not EVENT_ID.fullmatch(head):
            raise ValueError(f"line {number}: {head[:70]!r} is not a 64-character lowercase hex event id")
        if head in seen:
            raise ValueError(f"line {number}: duplicate event id {head}")
        seen.add(head)
        out.append((head, rest.strip()))
    return out


def _git(spec: Path, *args: str) -> str:
    return subprocess.run(["git", "-C", str(spec), *args], check=True, capture_output=True, text=True).stdout


def _entries(entries: List[Tuple[str, str]]) -> str:
    return "\n".join(f'    "{eid}",  # {note}' if note else f'    "{eid}",' for eid, note in entries)


def render(commit: str, sidesteps: List[Tuple[str, str]], rides: List[Tuple[str, str]]) -> str:
    return f'''"""The exemption lists of CYBERSPACE_V2.md section 6.16 and DECK-0001 section 5.8.

Generated by scripts/gen_grandfathered.py; do not edit by hand. Regenerate with

    python scripts/gen_grandfathered.py --spec /path/to/cyberspace --ref origin/master

Source: arkin0x/cyberspace at {commit}
  {SIDESTEPS} ({len(sidesteps)} ids): version 2 sidesteps (no mn tag)
  {RIDES} ({len(rides)} ids): rides without an mn tag

A listed event's roots and openings are accepted without re-checking them
(each was audited at Level 2 before it was listed); everything else about it
is checked as for any other event. An old-format event that is not listed is
invalid. The exemption is by event id, and an id is only as good as the event
it hashes, so is_grandfathered recomputes the id (NIP-01) before looking it up.
"""

from __future__ import annotations

import hashlib
import json
from typing import Any, Dict, FrozenSet

SPEC_COMMIT = "{commit}"

GRANDFATHERED_V2_SIDESTEPS: FrozenSet[str] = frozenset({{
{_entries(sidesteps)}
}})

GRANDFATHERED_V1_HYPERJUMPS: FrozenSet[str] = frozenset({{
{_entries(rides)}
}})


def is_grandfathered(event: Dict[str, Any], listed: FrozenSet[str]) -> bool:
    """Whether the event is on the list: its id is listed and is the NIP-01
    hash of the event itself, so a listed id pasted onto other content is not."""
    event_id = event.get("id")
    if event_id not in listed:
        return False
    payload = [0, event.get("pubkey"), event.get("created_at"), event.get("kind"), event.get("tags"), event.get("content")]
    serialized = json.dumps(payload, separators=(",", ":"), ensure_ascii=False).encode("utf-8")
    return hashlib.sha256(serialized).hexdigest() == event_id
'''


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--spec", type=Path, required=True, help="local clone of arkin0x/cyberspace")
    parser.add_argument("--ref", default="origin/master", help="git ref to read the lists at (default origin/master)")
    parser.add_argument("--out", type=Path, default=OUT)
    args = parser.parse_args()

    commit = _git(args.spec, "rev-parse", f"{args.ref}^{{commit}}").strip()
    sidesteps = parse_list(_git(args.spec, "show", f"{commit}:{SIDESTEPS}"))
    rides = parse_list(_git(args.spec, "show", f"{commit}:{RIDES}"))
    args.out.write_text(render(commit, sidesteps, rides))
    print(f"{args.out}: {len(sidesteps)} sidesteps, {len(rides)} rides, from {commit}")


if __name__ == "__main__":
    main()
